apiVersion: apps/v1
kind: Deployment
metadata:
  name: fireflies-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fireflies
  template:
    metadata:
      labels:
        app: fireflies
    spec:
      containers:
        - name: fireflies
          image: juliocodes/adminspace-fireflies:latest
          ports:
            - containerPort: 3001
          env:
            # Variables de entorno necesarias, por ejemplo:
            - name: PORT
              value: "3001"
            # Agrega aquí las variables sensibles si usas Secrets (recomendado)
            # - name: WEBHOOK_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: fireflies-secret
            #       key: WEBHOOK_SECRET
            # - name: SERVER_BASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: fireflies-secret
            #       key: SERVER_BASE_URL
